name: Build Flopcoin Wallet - Windows Static

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-static:
    name: Build Windows Static (daemon + CLI + TX + Qt GUI)
    runs-on: ubuntu-22.04
    env:
      HOST: x86_64-w64-mingw32
    steps:
      # -------------------- Checkout source --------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------- Install cross-compilation tools --------------------
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autotools-dev automake libtool pkg-config \
            bsdmainutils curl git g++-mingw-w64-x86-64 \
            qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools \
            libssl-dev libevent-dev libminiupnpc-dev \
            protobuf-compiler libprotobuf-dev

      # -------------------- Build depends for Windows x64 (static, Qt enabled, ZMQ disabled) --------------------
      - name: Build depends (Windows x64)
        run: |
          cd depends
          make -j$(nproc) HOST=$HOST NO_QT=0 NO_ZMQ=1 STATIC=1
          cd ..

      # -------------------- Configure Flopcoin --------------------
      - name: Configure Flopcoin
        run: |
          ./autogen.sh
          CONFIG_SITE=$PWD/depends/$HOST/share/config.site \
          ./configure --prefix=/ \
            --host=$HOST \
            --disable-shared \
            --enable-static \
            --disable-zmq \
            --disable-tests \
            --disable-bench

      # -------------------- Build Flopcoin --------------------
      - name: Build Flopcoin
        run: make -j$(nproc)

      # -------------------- Upload all Windows binaries as a single artifact --------------------
      - name: Upload Windows static binaries
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-windows-static
          path: |
            src/flopcoind.exe
            src/flopcoin-cli.exe
            src/flopcoin-tx.exe
            src/qt/flopcoin-qt.exe
