name: Build Flopcoin Wallet - macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool miniupnpc openssl pkg-config protobuf@21 \
                       qt@5 zeromq qrencode librsvg boost berkeley-db@5 libevent
          brew link protobuf@21

      # 🔍 Debug step: show where Boost and its libraries are installed
      - name: Debug Boost installation
        run: |
          echo "BOOST PREFIX: $(brew --prefix boost)"
          ls -R $(brew --prefix boost) || true
          ls -l $(brew --prefix boost)/lib | grep boost_system || true

      - name: Configure & Build
        run: |
          BOOST_ROOT=$(brew --prefix boost)
          BOOST_INCLUDEDIR=$BOOST_ROOT/include
          BOOST_LIBDIR=$BOOST_ROOT/lib

          OPENSSL_ROOT=$(brew --prefix openssl)
          QT_DIR=$(brew --prefix qt@5)

          export CPPFLAGS="-I$BOOST_INCLUDEDIR -I$OPENSSL_ROOT/include"
          export LDFLAGS="-L$BOOST_LIBDIR -L$OPENSSL_ROOT/lib"
          export PKG_CONFIG_PATH="$QT_DIR/lib/pkgconfig:$OPENSSL_ROOT/lib/pkgconfig"
          export PATH="$QT_DIR/bin:$PATH"

          ./autogen.sh
          ./configure \
            --with-gui=qt5 \
            --with-boost=$BOOST_ROOT \
            --with-boost-libdir=$BOOST_LIBDIR \
            --disable-tests --disable-bench
          make -j$(sysctl -n hw.ncpu)

      - name: Upload macOS daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoind-macos
          path: src/flopcoind

      - name: Upload macOS Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-macos
          path: src/qt/flopcoin-qt
