name: Build Flopcoin Wallet -MAC

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # -------------------- macOS --------------------
  build-macos:
    name: Build macOS (daemon + Qt GUI)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool boost openssl berkeley-db4 pkg-config libevent qt@5 miniupnpc protobuf
          echo "BOOST_ROOT=$(brew --prefix boost)" >> $GITHUB_ENV
          echo "OPENSSL_ROOT=$(brew --prefix openssl)" >> $GITHUB_ENV
          echo "QT_DIR=$(brew --prefix qt@5)" >> $GITHUB_ENV

      - name: Build Flopcoin
        run: |
          export LDFLAGS="-L$BOOST_ROOT/lib -L$OPENSSL_ROOT/lib"
          export CPPFLAGS="-I$BOOST_ROOT/include -I$OPENSSL_ROOT/include"
          export PKG_CONFIG_PATH="$BOOST_ROOT/lib/pkgconfig:$OPENSSL_ROOT/lib/pkgconfig"
          export PATH="$QT_DIR/bin:$PATH"

          ./autogen.sh
          ./configure --with-gui=qt5 --with-boost-libdir=$BOOST_ROOT/lib
          make -j$(sysctl -n hw.ncpu)

      - name: Upload macOS daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: src/flopcoind

      - name: Upload macOS Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-macos
          path: src/qt/flopcoin-qt
