name: Build Flopcoin Wallet - macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool miniupnpc openssl pkg-config protobuf@21 \
                       qt@5 zeromq qrencode librsvg boost berkeley-db@5 libevent
          brew link protobuf@21

      - name: Debug Boost install
        run: |
          echo "BOOST PREFIX: $(brew --prefix boost)"
          ls -l $(brew --prefix boost)/lib | grep boost_system || true

      - name: Configure & Build
        run: |
          BOOST_ROOT=$(brew --prefix boost)
          OPENSSL_ROOT=$(brew --prefix openssl)
          QT_DIR=$(brew --prefix qt@5)

          export CPPFLAGS="-I$BOOST_ROOT/include -I$OPENSSL_ROOT/include"
          export LDFLAGS="-L$BOOST_ROOT/lib -L$OPENSSL_ROOT/lib -lboost_system"
          export PKG_CONFIG_PATH="$QT_DIR/lib/pkgconfig:$OPENSSL_ROOT/lib/pkgconfig"
          export PATH="$QT_DIR/bin:$PATH"

          ./autogen.sh
          ./configure \
            --with-gui=qt5 \
            --with-boost=$BOOST_ROOT \
            --with-boost-libdir=$BOOST_ROOT/lib \
            --disable-tests --disable-bench
          make -j$(sysctl -n hw.ncpu)

      - name: Upload macOS binaries
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: |
            src/flopcoind
            src/qt/flopcoin-qt
