name: Build Flopcoin Wallet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # -------------------- Linux --------------------
  build-linux:
    name: Build Linux (daemon + Qt GUI)
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential libtool autotools-dev automake pkg-config \
            libssl-dev libboost-all-dev libdb++-dev libevent-dev bsdmainutils git \
            qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools libminiupnpc-dev
      - name: Build Flopcoin
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5
          make -j$(nproc)
      - name: Upload Linux daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-linux
          path: src/flopcoind
      - name: Upload Linux Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-linux
          path: src/flopcoin-qt

  # -------------------- Windows --------------------
  build-windows:
    name: Build Windows (daemon + Qt GUI)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
      - name: Install vcpkg and dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg install boost:x64-windows openssl:x64-windows qt5:x64-windows miniupnpc:x64-windows
      - name: Build Flopcoin
        run: msbuild src\flopcoin.sln /p:Configuration=Release
      - name: Upload Windows daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-windows
          path: src\Release\flopcoind.exe
      - name: Upload Windows Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-windows
          path: src\Release\flopcoin-qt.exe

  # -------------------- macOS --------------------
  build-macos:
    name: Build macOS (daemon + Qt GUI)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool boost openssl berkeley-db4 pkg-config libevent qt5 miniupnpc
          export BOOST_ROOT=/usr/local/opt/boost
          export PATH=$BOOST_ROOT/bin:$PATH
          export LDFLAGS="-L$BOOST_ROOT/lib -L/usr/local/opt/openssl/lib"
          export CPPFLAGS="-I$BOOST_ROOT/include -I/usr/local/opt/openssl/include"
          export PKG_CONFIG_PATH="$BOOST_ROOT/lib/pkgconfig"
          export QT5_DIR="/usr/local/opt/qt@5"
          export PATH="$QT5_DIR/bin:$PATH"
      - name: Build Flopcoin
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5
          make -j$(sysctl -n hw.ncpu)
      - name: Upload macOS daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: src/flopcoind
      - name: Upload macOS Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-macos
          path: src/flopcoin-qt
