name: Build Flopcoin Wallet - macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS (daemon + Qt GUI)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies via Homebrew
        run: |
          brew update
          brew install autoconf automake libtool miniupnpc openssl pkg-config protobuf@21 \
                       qt@5 zeromq qrencode librsvg boost berkeley-db@5 libevent
          brew link --force protobuf@21
          export PATH="$(brew --prefix qt@5)/bin:$PATH"

      - name: Diagnose Boost
        run: |
          BOOST_PREFIX=$(brew --prefix boost)
          echo "Boost prefix: $BOOST_PREFIX"
          echo "Listing Boost libraries:"
          ls -lh $BOOST_PREFIX/lib | grep boost || echo "⚠️ No Boost libs found!"

      - name: Autogen and Configure
        run: |
          BOOST_PREFIX=$(brew --prefix boost)
          BOOST_LIBDIR="$BOOST_PREFIX/lib"
          echo "Using Boost from: $BOOST_PREFIX"
          ./autogen.sh
          ./configure --with-gui=qt5 \
                      --with-boost=$BOOST_PREFIX \
                      --with-boost-libdir=$BOOST_LIBDIR

      - name: Build Flopcoin
        run: make -j$(sysctl -n hw.ncpu)

      - name: Upload macOS daemon
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: src/flopcoind

      - name: Upload macOS Qt GUI
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-macos
          path: src/qt/flopcoin-qt
