name: Build Flopcoin Wallet - Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (daemon + Qt GUI) - Fully Static
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cross-compile toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libtool autotools-dev automake pkg-config \
            bsdmainutils curl git g++-mingw-w64-x86-64

      - name: Build depends (Windows x86_64)
        run: |
          cd depends
          make HOST=x86_64-w64-mingw32 -j$(nproc) \
            NO_QT=0    # ensure Qt gets built
          cd ..

      - name: Configure for Windows (static)
        run: |
          ./autogen.sh
          CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site \
          ./configure \
            --prefix=/ \
            --host=x86_64-w64-mingw32 \
            --with-gui=qt5 \
            LDFLAGS="-static"

      - name: Build Flopcoin (Windows)
        run: make -j$(nproc)

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-windows
          path: |
            src/flopcoind.exe
            src/flopcoin-cli.exe
            src/flopcoin-tx.exe
            src/qt/flopcoin-qt.exe
