name: Build Flopcoin Wallet - macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update

          # Prefer Boost 1.83 if available, fallback to latest (1.84+)
          if brew info boost@1.83 &>/dev/null; then
            brew install boost@1.83
            BOOST_PREFIX=$(brew --prefix boost@1.83)
          else
            brew install boost
            BOOST_PREFIX=$(brew --prefix boost)
          fi

          brew install autoconf automake libtool miniupnpc openssl pkg-config protobuf@21 \
                       qt@5 zeromq qrencode librsvg berkeley-db@5 libevent create-dmg
          brew link protobuf@21

          echo "BOOST_PREFIX=$BOOST_PREFIX" >> $GITHUB_ENV
          echo "OPENSSL_PREFIX=$(brew --prefix openssl)" >> $GITHUB_ENV
          echo "QT_PREFIX=$(brew --prefix qt@5)" >> $GITHUB_ENV

      - name: Set environment
        run: |
          echo "CPPFLAGS=-I$BOOST_PREFIX/include -I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$BOOST_PREFIX/lib -L$OPENSSL_PREFIX/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$QT_PREFIX/lib/pkgconfig" >> $GITHUB_ENV
          echo "PATH=$QT_PREFIX/bin:$PATH" >> $GITHUB_ENV

      - name: Autogen
        run: ./autogen.sh

      - name: Configure
        run: |
          ./configure \
            --with-gui=qt5 \
            --with-boost=$BOOST_PREFIX \
            --with-boost-libdir=$BOOST_PREFIX/lib \
            --with-openssl=$OPENSSL_PREFIX \
            BOOST_CPPFLAGS="-I$BOOST_PREFIX/include" \
            BOOST_LDFLAGS="-L$BOOST_PREFIX/lib" \
            PKG_CONFIG_PATH=$PKG_CONFIG_PATH \
            CPPFLAGS="$CPPFLAGS" \
            LDFLAGS="$LDFLAGS"

      - name: Build
        run: make -j$(sysctl -n hw.ncpu)

      - name: Upload flopcoind
        uses: actions/upload-artifact@v4
        with:
          name: flopcoind-macos
          path: src/flopcoind

      - name: Upload flopcoin-qt
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-macos
          path: src/qt/flopcoin-qt
