name: macOS Build (Flopcoin-Qt)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-macos:
    runs-on: macos-13   # Intel
    strategy:
      matrix:
        arch: [x86_64, arm64]   # cover Intel & Apple Silicon
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew update

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool miniupnpc openssl pkg-config \
                       protobuf@21 qt@5 zeromq qrencode librsvg boost@1.76 \
                       berkeley-db@5 libevent
          brew link --force protobuf@21
          brew link --force qt@5
          brew link --force boost@1.76

      - name: Build Flopcoin
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5 \
                      --with-boost=$(brew --prefix boost@1.76) \
                      --with-qt=$(brew --prefix qt@5) \
                      --with-bdb=$(brew --prefix berkeley-db@5) \
                      --with-incompatible-bdb
          make -j$(sysctl -n hw.ncpu)

      - name: Package .app bundle
        run: |
          mkdir -p artifacts
          cp src/qt/flopcoin-qt artifacts/
          ls -lh artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-qt-${{ matrix.arch }}
          path: artifacts/*
