name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install boost@1.83 qt@5 berkeley-db@4 automake libtool pkg-config gnu-tar

          # Force macOS to use correct Qt and Boost paths
          echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> $GITHUB_ENV
          echo 'export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig:$PKG_CONFIG_PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/opt/homebrew/opt/boost@1.83/lib -L/opt/homebrew/opt/berkeley-db@4/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/opt/homebrew/opt/boost@1.83/include -I/opt/homebrew/opt/berkeley-db@4/include"' >> $GITHUB_ENV
          echo 'export CC="clang"' >> $GITHUB_ENV
          echo 'export CXX="clang++"' >> $GITHUB_ENV

      - name: Build Flopcoin Core
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5 --with-boost=/opt/homebrew/opt/boost@1.83 --with-incompatible-bdb
          make -j$(sysctl -n hw.logicalcpu)

      - name: Package
        run: |
          make install DESTDIR=$PWD/dest
          tar -czf flopcoin-macos.tar.gz -C dest .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: flopcoin-macos.tar.gz
