name: macOS Build

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (brew)
        run: |
          brew update
          brew install autoconf automake libtool pkg-config \
                       miniupnpc openssl protobuf@21 qt@5 zeromq qrencode \
                       librsvg boost berkeley-db@5 libevent

          # Force link protobuf (needed for bitcoin-like builds)
          brew link protobuf@21

      - name: Configure Boost env
        run: |
          # Homebrew boost paths (Intel vs Apple Silicon)
          BOOST_ROOT_INTEL=/usr/local/opt/boost
          BOOST_ROOT_ARM=/opt/homebrew/opt/boost

          if [ -d "$BOOST_ROOT_ARM" ]; then
            export BOOST_ROOT=$BOOST_ROOT_ARM
          else
            export BOOST_ROOT=$BOOST_ROOT_INTEL
          fi

          export BOOST_CPPFLAGS="-I$BOOST_ROOT/include"
          export BOOST_LDFLAGS="-L$BOOST_ROOT/lib"

          echo "BOOST_CPPFLAGS=$BOOST_CPPFLAGS" >> $GITHUB_ENV
          echo "BOOST_LDFLAGS=$BOOST_LDFLAGS" >> $GITHUB_ENV

      - name: Build Flopcoin
        run: |
          ./autogen.sh
          ./configure --with-gui=qt5 \
            BOOST_CPPFLAGS="$BOOST_CPPFLAGS" BOOST_LDFLAGS="$BOOST_LDFLAGS"
          make -j$(sysctl -n hw.ncpu)

      - name: Package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-macos
          path: src/{flopcoin-qt,flopcoind}
