name: Build Flopcoin Wallet - Windows Static Qt

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-static-qt:
    name: Build Windows Static (daemon + fully static Qt GUI)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup WSL and Ubuntu
        run: |
          wsl --list --verbose || echo "WSL installed"
          wsl --install -d Ubuntu-22.04 || echo "Ubuntu already installed"

      - name: Install build dependencies inside WSL
        run: |
          wsl bash -c "
          sudo apt-get update &&
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
            bsdmainutils curl git qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools \
            libssl-dev libboost-all-dev libdb++-dev libevent-dev libminiupnpc-dev \
            protobuf-compiler libprotobuf-dev mingw-w64
          "

      - name: Build depends (Windows x64, fully static)
        run: |
          wsl bash -c "
          cd depends &&
          make -j\$(nproc) HOST=x86_64-w64-mingw32 NO_QT=0 NO_ZMQ=1 STATIC=1 \
            QT_STATIC=1 &&
          cd ..
          "

      - name: Configure Flopcoin for fully static build
        run: |
          wsl bash -c "
          ./autogen.sh &&
          CONFIG_SITE=\$PWD/depends/x86_64-w64-mingw32/share/config.site \
          ./configure --host=x86_64-w64-mingw32 --prefix=/ \
            --disable-shared --enable-static \
            --disable-zmq --disable-tests --disable-bench \
            --with-gui=qt5 --enable-static-qt
          "

      - name: Build Flopcoin (Windows static)
        run: |
          wsl bash -c "make -j\$(nproc)"

      - name: Collect Windows binaries
        run: |
          mkdir -p flopcoin-windows-static
          cp src/flopcoind.exe flopcoin-windows-static/
          cp src/flopcoin-cli.exe flopcoin-windows-static/
          cp src/flopcoin-tx.exe flopcoin-windows-static/
          cp src/qt/flopcoin-qt.exe flopcoin-windows-static/

      - name: Upload Windows static binaries artifact
        uses: actions/upload-artifact@v4
        with:
          name: flopcoin-windows-static
          path: flopcoin-windows-static/
